### PR TITLE
Fixed missing superclass and prototype for AbsoluteArcPath

### PR DESCRIPTION
**Pull request by gsvarovsky**
A minor bug fix and associated test for you :)

### CODE REVIEW

**Comment by jfschwarz** [comment]
Thank you! :)

**Comment by gsvarovsky** [comment]
You're welcome. Thanks for the library!

**Comment by gsvarovsky** [comment]
Can you push a version to npm when you get the chance please?

**Comment by jfschwarz** [comment]
Sure thing! v0.2.5 coming your way...

**Comment by gsvarovsky** [comment]
Super.

**Pull request merged**
